language: node_js
node_js:
  - 'node'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install: yarn --ignore-platform
script:
  - npm test
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
